#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'bug2-navigation','console_scripts','bug2_navigation'
__requires__ = 'bug2-navigation'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('bug2-navigation', 'console_scripts', 'bug2_navigation')()
    )
